name: CI Maven pour essais

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: mvn -U --version
    - name: commande ls
      run: ls -f
    - name: Lancer la compilation
      run: mvn clean compile
    - name: Lancer le maven site
      run: mvn site
    - name: ls sur racine
      run: ls -f
    - name: ls sur target/site
      run: ls -f target/site
    - name: setup git config
      run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
    - name: commit
      run: |
          # Stage the files, commit and push
          git add target/site/*
          git commit -m "Maven Site Copy commit"
          git push origin master
