name: CI Github Pages Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
          env = {
          BUILD_DIR = "/demo"
          }
          secrets = ["GH_PAT"]

